name: trace_it
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  provider: ^6.0.5
  confetti: ^0.6.0
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.9.0
  firebase_core: ^2.24.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  analyzer: ^6.4.1
flutter:
  uses-material-design: true
